---
title: "Function-AED-UAS"
author: "Angga Fathan Rofiqy"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

# Function

### Install Load Function

```{r}
#                      -=( Install & Load Package Function )=-
install_load <- function (package1, ...)  {   

   # convert arguments to vector
   packages <- c(package1, ...)

   # start loop to determine if each package is installed
   for(package in packages){

       # if package is installed locally, load
       if(package %in% rownames(installed.packages()))
          do.call('library', list(package))

       # if package is not installed locally, download, then load
       else {
          install.packages(package)
          do.call("library", list(package))
       }
   } 
}
```

### Outlier Function

```{r}
#                            -=( Is outlier? Funciton )=-
is_outlier <- function(x) {
  return(x < quantile(x,0.25) -1.5*IQR(x) | x > quantile(x,0.75) +1.5*IQR(x))
}
```

### Ggplot Stat Atribure Function

```{r}
#                      -=( Ggplot Stat Attribute Funciton )=-
gstat <- function(dt){
  install_load("dplyr","tibble")
  
  #Set Data Frame
  dt <- data.frame(obs = dt[[1]], dat = dt[[2]], row.names = dt[[1]])
  
  #ID/obs outlier (oo)
  oo <- dt %>%
  rownames_to_column(var = "outlier") %>%
  mutate(is_outlier = if_else(is_outlier(dat), dat, as.numeric(NA))) %>%
  mutate(outlier = if_else(is.na(is_outlier) | is_outlier == max(dat) 
                           | is_outlier == min(dat), as.numeric(NA), 
                             as.numeric(outlier)),
         is_outlier = if_else(is_outlier == max(dat) 
                              | is_outlier == min(dat), 
                                as.numeric(NA), is_outlier))
  
  #Obs Minimum
  om <- data.frame(min = ifelse(dt$dat == min(dt$dat), dt$obs, NA), 
                   min_val = ifelse(dt$dat == min(dt$dat), min(dt$dat), NA))
  #Obs Maximum
  omx <- data.frame(max = ifelse(dt$dat == max(dt$dat), dt$obs, NA), 
                    max_val = ifelse(dt$dat == max(dt$dat), max(dt$dat), NA))
  #Binding together
  gs <- cbind(oo, om, omx)
  
  #Calc Mean
  mean <- data.frame(mean = round(mean(dt$dat), 2))
  
  #Make it list
  gs <- list(gs, mean)
return(gs)
}
```

### Default Color Palette

```{r}
#                           -=( Default Color Palette )=-
colord <- data.frame(
  f = c('#75bfc8', 'Fill color'),        c = c('#444442', 'Stroke color'),
  oc = c('#0b5f6a', 'Outlier color'),    min = c('#0b5f6a', 'Minimum value color'),
  max = c('#0b5f6a', 'Max value color'), med = c('#c3ac8b', 'Median value color'),
  iqr = c('#c3ac8b', 'IQR3 Value'),      mean = c('#608981', 'Mean Marker'),
  ooc = c('#0b5f6a', 'Oulier Obs color'), 
  ovc = c('#0b5f6a', 'Oulier Value color'), v = c('#c3eca2', 'Violin'),
  meanv = c('#608981', 'Mean Value'),    moc = c('#0b5f6a', 'Min Max Obs'),
  stringsAsFactors = FALSE
)
```

```{r}
#                         -=( Default Color Palette 2 )=-
colord2 <- data.frame(
  f = c('#625bcb', 'Fill color'),        c = c('#444442', 'Stroke color'),
  oc = c('#0e1d60', 'Outlier color'),    min = c('#0e1d60', 'Minimum value color'),
  max = c('#0e1d60', 'Max value color'), med = c('#144fa8', 'Median value color'),
  iqr = c('#144fa8', 'IQR3 Value'),      mean = c('#cfcff4', 'Mean Marker'),
  ooc = c('#0e1d60', 'Oulier Obs color'), 
  ovc = c('#0e1d60', 'Oulier Value color'), v = c('#89dff6', 'Violin'),
  meanv = c('#cfcff4', 'Mean Value'),    moc = c('#0e1d60', 'Min Max Obs'),
  stringsAsFactors = FALSE
)
```

```{r}
#                         -=( Default Color Palette 3 )=-
colord3 <- data.frame(
  f = c('#f27a01', 'Fill color'),        c = c('#444442', 'Stroke color'),
  oc = c('#d13b01', 'Outlier color'),    min = c('#d13b01', 'Minimum value color'),
  max = c('#d13b01', 'Max value color'), med = c('#dd5d31', 'Median value color'),
  iqr = c('#dd5d31', 'IQR3 Value'),      mean = c('#fefd82', 'Mean Marker'),
  ooc = c('#d13b01', 'Oulier Obs color'), 
  ovc = c('#d13b01', 'Oulier Value color'), v = c('#53b1b1', 'Violin'),
  meanv = c('#fefd82', 'Mean Value'),    moc = c('#d13b01', 'Min Max Obs'),
  stringsAsFactors = FALSE
)
```

### Label & Title

```{r}
#                            -=( Default Label/Title )=-
lab1 <- data.frame(title='Distribution of Data X', ylab='', xlab='Data X')
```

### Ggplot theme1

```{r}
install_load('ggplot2')
theme1 <- list(
  guides(fill="none") , #No Legends
  theme(
  text = element_text(size = 66),
  axis.text.y = element_text(vjust = .5, face = "bold"),
  plot.title = element_text(hjust = 0.5),
  plot.subtitle = element_text(hjust = 0.5),
  panel.background = element_rect(fill = 'transparent'),
  plot.background = element_rect(fill='transparent', color=NA),
  panel.grid.major = element_line(colour = "grey50"),
  axis.line = element_line(linewidth = 5, colour = "grey80"))
)
```

### Box Plot Function

```{r}
#                           -=( Box Plot Function )=-
boxp <- function(dt, cp=colord, labs=lab1){ #data, color palette, label
  install_load('ggplot2')
  gs <- gstat(dt)
  b <- ggplot(data=gs[[1]], aes(y="", x=dat)) + 
        #Violin Plot
        geom_violin(scale="count", fill=cp$v[1], color=NA, alpha=0.25) +
        #Box Plot
        geom_boxplot(fill=cp$f[1], color=cp$c[1],
                     outlier.size=15, outlier.color=cp$oc[1], 
                     alpha=0.7,notch=T) +
        #Jitter
        geom_jitter(color=cp$oc[1], width=0.2, size=5, shape=17, alpha=0.25) +
        #Minimum Marker
        stat_summary(geom="point", fun='min',
                     aes(label=sprintf("%1.1f", after_stat(x))), 
                     position=position_nudge(y=0.05), size=15, color=cp$oc[1]) +
        #Max Marker
        stat_summary(geom="point", fun='max',
                     aes(label=sprintf("%1.1f", after_stat(x))), 
                     position=position_nudge(y=0.05), size=15, color=cp$oc[1]) +
        #Median Value
        stat_summary(geom="text", fun=median,
                     aes(label=sprintf("%1.1f", after_stat(x))),
                     position=position_nudge(y=0.425), size=16, color=cp$med[1]) +
        #IQR1 Value
        stat_summary(geom="text", fun="quantile", fun.args=list(probs=0.25),
                     aes(label=sprintf("%1.1f", after_stat(x))),
                     position=position_nudge(y=-0.425), size=16, color=cp$iqr[1]) +
        #IQR3 Value
        stat_summary(geom="text", fun="quantile", fun.args=list(probs=0.75),
                     aes(label=sprintf("%1.1f", after_stat(x))),
                     position=position_nudge(y=-0.425), size=16, color=cp$iqr[1]) +
        #Mean Marker
        stat_summary(fun='mean', geom="point",colour=cp$mean[1], 
                     shape=18, size=16, alpha=0.75) +
        #Title
        ggtitle(labs$title) + 
        theme(plot.title = element_text(hjust = 0.5)) + #Title Position
        #Labels
        ylab(labs$ylab) + xlab(labs$xlab) +
        #Oulier Province
        geom_text(aes(label=outlier),na.rm=TRUE,nudge_x=0.05, 
                  angle=45, size=12, vjust=0.75, hjust=1.15, color=cp$ooc[1]) +
        #Oulier Value
        geom_text(aes(label=is_outlier),na.rm=TRUE,nudge_x=0.05, 
                  angle=45, size=16, vjust=0.25, hjust=-0.5, color=cp$ovc[1]) +
        #Minimum Province
        geom_text(aes(label=ifelse(!is.na(min),paste0("Min : ",min_val,'\n',min),
                                   paste(""))), 
                  na.rm=FALSE, nudge_x=0.05,
                  angle=45, size=12, vjust=1.15, hjust=0.5, color=cp$moc[1]) +
        #Max Province
        geom_text(aes(label=ifelse(!is.na(max),paste0("Max : ",max_val,'\n',max),
                                   paste(""))), 
                  na.rm=FALSE, nudge_x=0.05,
                  angle=45, size=12, vjust=1.15, hjust=0.5, color=cp$moc[1]) +
        #Mean Value
        geom_text(data = gs[[2]], aes(label = paste0("Mean : ",mean), x = mean),
                  angle=45, size=16, vjust=-0.5, hjust=0.5, color=cp$mean[1]) + 
        #Theme
        theme1
return(b)
}
```

# Example

### Data Entry

```{r}
install_load('gsheet')
data <- gsheet2tbl('https://docs.google.com/spreadsheets/d/18xpT0Zmz68owANxIUppAP6dvCs52YK8J/edit#gid=996271162')
data <- cbind(obs=1:nrow(data),data)
View(data)
```

### Data X

```{r dpi=300, fig1, fig.height = 17, fig.width = 50, fig.align = "center"}
#Look above this text. ^ You can change the height & width of this fig as you want
#Call The Boxplot Function
c1.1 <- boxp(data[,c(1,1+1)]); c1.1
```

### Data Y

```{r dpi=300, fig1, fig.height = 17, fig.width = 50, fig.align = "center"}
#Change the Title and x axis label
tl <- "Distribution of Data Y"; xl <- "Data Y"
label <- data.frame(title=tl, ylab='', xlab=xl)
#Change the color palette to colord2
c1.2 <- boxp(data[,c(1,1+2)], labs=label, cp=colord2); c1.2
```

### Data Z

```{r dpi=300, fig1, fig.height = 17, fig.width = 50, fig.align = "center"}
#Change the Title and x axis label
tl <- "Distribution of Data Z"; xl <- "Data Z"
label <- data.frame(title=tl, ylab='', xlab=xl)
#Change the color palette to colord2
c1.3 <- boxp(data[,c(1,1+3)], labs=label, cp=colord3); c1.3
```

### Data X and Y

```{r dpi=300, fig1, fig.height = 34, fig.width = 50, fig.align = "center"}
#Change the fig height ^ to 34
#Use plot_grid to combine the chart
install_load("cowplot")
c12 <- plot_grid(c1.1, c1.2,
               align="hv", axis="tblr", nrow = 2, scale = c(0.9,0.9)); c12
```

### Data Z and Y

```{r dpi=300, fig1, fig.height = 34, fig.width = 50, fig.align = "center"}
#You can combine it as you want
install_load("cowplot")
c32 <- plot_grid(c1.3, c1.2,
               align="hv", axis="tblr", nrow = 2, scale = c(0.9,0.9)); c32
```

#### Data X Y Z

```{r dpi=300, fig1, fig.height = 51, fig.width = 50, fig.align = "center"}
#Change the fig height ^ to 51
install_load("cowplot")
c1 <- plot_grid(c1.1, c1.2, c1.3,       #Change nrow and scale
               align="hv", axis="tblr", nrow = 3, scale = c(0.9,0.9,0.9)); c1
```
